### ISSUE TITLE
Update Federalist 1-pager document and pricing

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist-team#18]
#### User Story

As a potential customer of Federalist, I would like to have a document that explains what Federalist provides and for how much. I will then be able to share this document with my *colleagues* and *supervisors*.

#### Open Question

- What information is necessary to show my supervisors?
- Should we add testimonials?
- Should we use the Cloud/Login template?

#### Tasks
- [x] Update enhanced pricing 
- [x] Add implementation/custom pricing
- [x] Add new value proposition in the front page. @amirahaziz 
- [x] Finalize copy edit and release on website

#### Background
Login & Cloud are working on similar documentation to send out as a simple briefing document after intro business calls. I think we should work on something as well with similar templates. Its a way to get customers excited abut the product!

**Comment by amirahaziz** [comment]
Current draft: 
https://docs.google.com/document/d/1HeLanvq-0zoKyWBNwdXpB0NXT4GLnP6rON9ZzCnN0nk/edit?ts=5c4b59df

**Comment by eddietejeda** [comment]
This is in progress. I've cleaned up the document quite a bit, but it still needs some work. Amirah, I will let you know when I need your feedback.

**Comment by eddietejeda** [comment]
It's live! https://federalist.18f.gov/assets/documents/Federalist-Proposal.pdf
