### ISSUE TITLE
Build out Federalist success stories 

### ISSUE THREAD

**Issue by amirahaziz** [18F/federalist-team#24]
#### User Story

In an effort to communicate the business value of Federalist to our stakeholders and current customers, it may be a good idea to build on current customers successes of Federalist work we have done with them. Would be interesting to learn of any key dollar or time savings after our work was over, plus their experience with working with Federalist (impact). 

CoE: https://coe.gsa.gov/
AFWERX: https://afwerx.af.mil

#### Related:
https://github.com/18F/federalist/issues/1801

#### TODO

- [x] Conduct interviews
- [x] Share interview notes with team
- [x] Write case studies in Google Doc (https://docs.google.com/document/d/1-KyjkaB5HCwWCVmths6pPOOL9LCoj-4pRisA-LJMTew/edit)
- [x] Finalize language in Google Doc (working with Jeff Durland) NEW DOC: https://docs.google.com/document/d/1-Dzw5uPHfu-aALvNDPst-15_8Nm3kgEtpzjhcjDc5fQ/edit
- [x] Update website contents (working with Austin on design of PDFs)

**Comment by amirahaziz** [comment]
Here are the completed success stories:

https://docs.google.com/document/d/1-KyjkaB5HCwWCVmths6pPOOL9LCoj-4pRisA-LJMTew/edit

**Comment by eddietejeda** [comment]
Design issue being tracked here: https://github.com/18F/design-lab/issues/57

**Comment by eddietejeda** [comment]
Will connect with @amirahaziz with @austinhernandez

**Comment by amirahaziz** [comment]
I scheduled time with Jeff to go over the content of the finished success stories on Monday 4/1.

**Comment by amirahaziz** [comment]
Met with Jeff today, he is going to review this doc and make this changes by the end of the week:
https://docs.google.com/document/d/1-Dzw5uPHfu-aALvNDPst-15_8Nm3kgEtpzjhcjDc5fQ/edit

**Comment by amirahaziz** [comment]
Jeff and I finished the content for the stories...waiting for Austin to get back to us on design

**Comment by eddietejeda** [comment]
@eddietejeda should check in with Austin.

**Comment by amirahaziz** [comment]
Templates are done! Final first drafts here: https://docs.google.com/presentation/d/1Awuileq6k7bD7hkNx8BfWiSk3_l6gqTenAHzP227UfE/edit#slide=id.g5670649836_0_21
